-- PostgreSQL reference schema for a future server API. Not connected to the local demo.
CREATE TABLE restaurants (id uuid PRIMARY KEY, name text NOT NULL, address text, gst_number text, timezone text NOT NULL DEFAULT 'Asia/Kolkata');
CREATE TABLE users (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), name text NOT NULL, email text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('owner','cashier','waiter','kitchen')), active boolean NOT NULL DEFAULT true);
CREATE TABLE dining_tables (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), number text NOT NULL, capacity integer NOT NULL CHECK(capacity > 0), UNIQUE(restaurant_id,number));
CREATE TABLE food_categories (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), name text NOT NULL, UNIQUE(restaurant_id,name));
CREATE TABLE food_items (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), category_id uuid REFERENCES food_categories(id), name text NOT NULL, price numeric(12,2) NOT NULL CHECK(price>=0), parcel_price numeric(12,2) NOT NULL CHECK(parcel_price>=0), tax_rate numeric(5,2) NOT NULL CHECK(tax_rate BETWEEN 0 AND 100), vegetarian boolean NOT NULL, available boolean NOT NULL DEFAULT true, image_url text);
CREATE TABLE customers (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), name text, mobile text);
CREATE TABLE orders (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), order_number bigint NOT NULL, order_type text NOT NULL CHECK(order_type IN ('DINE-IN','PARCEL')), table_id uuid REFERENCES dining_tables(id), customer_id uuid REFERENCES customers(id), guests integer NOT NULL DEFAULT 0, status text NOT NULL CHECK(status IN ('New','Preparing','Ready','Served','Cancelled')), discount numeric(12,2) NOT NULL DEFAULT 0 CHECK(discount>=0), parcel_charge numeric(12,2) NOT NULL DEFAULT 0 CHECK(parcel_charge>=0), created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(restaurant_id,order_number));
-- Snapshot name/category/price/tax: later menu edits must not alter historical bills.
CREATE TABLE order_items (id uuid PRIMARY KEY, order_id uuid NOT NULL REFERENCES orders(id), food_id uuid REFERENCES food_items(id), food_name text NOT NULL, category_name text NOT NULL, unit_price numeric(12,2) NOT NULL CHECK(unit_price>=0), tax_rate numeric(5,2) NOT NULL CHECK(tax_rate BETWEEN 0 AND 100), quantity integer NOT NULL CHECK(quantity>0));
CREATE TABLE bills (id uuid PRIMARY KEY, order_id uuid NOT NULL UNIQUE REFERENCES orders(id), subtotal numeric(12,2) NOT NULL, discount numeric(12,2) NOT NULL DEFAULT 0, tax numeric(12,2) NOT NULL, parcel_charge numeric(12,2) NOT NULL DEFAULT 0, total numeric(12,2) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payments (id uuid PRIMARY KEY, bill_id uuid NOT NULL REFERENCES bills(id), mode text NOT NULL CHECK(mode IN ('Cash','UPI','Card')), amount numeric(12,2) NOT NULL CHECK(amount>=0), idempotency_key text NOT NULL UNIQUE, paid_at timestamptz NOT NULL DEFAULT now(), collected_by uuid REFERENCES users(id));
CREATE TABLE discounts (id uuid PRIMARY KEY, restaurant_id uuid NOT NULL REFERENCES restaurants(id), name text NOT NULL, amount numeric(12,2) NOT NULL CHECK(amount>=0), active boolean NOT NULL DEFAULT true);
CREATE INDEX orders_restaurant_date ON orders(restaurant_id,created_at);
CREATE INDEX order_items_order ON order_items(order_id);
CREATE VIEW daily_reports AS SELECT o.restaurant_id, (o.created_at AT TIME ZONE r.timezone)::date AS day, count(*) AS paid_orders, sum(b.total) AS sales, sum(b.tax) AS tax FROM orders o JOIN restaurants r ON r.id=o.restaurant_id JOIN bills b ON b.order_id=o.id WHERE o.status <> 'Cancelled' AND EXISTS (SELECT 1 FROM payments p WHERE p.bill_id=b.id GROUP BY p.bill_id HAVING sum(p.amount)>=b.total) GROUP BY o.restaurant_id,(o.created_at AT TIME ZONE r.timezone)::date;
-- Server implementation must authorize restaurant/role access, recompute totals,
-- validate table occupancy, and commit bills/payments atomically. Never trust client totals.
